# database.yml
database:
  enabled: false       # 是否启用MySQL（true=启用，false=禁用）
  host: localhost      # 数据库服务器地址
  port: 3306           # 数据库端口
  database: emcshop    # 数据库名称
  username: root       # 数据库用户名
  password: ""         # 数据库密码
  # 连接池配置
  pool:
    maximum-pool-size: 10
    minimum-idle: 5
    connection-timeout: 30000
    idle-timeout: 600000
    max-lifetime: 1800000